### ISSUE TITLE
https://www.x3dom.org/ Certificate Expired 20 August 2018

### ISSUE THREAD

**Issue by jamesleesaunders** [x3dom/x3dom#889]
www.x3dom.org
https Root Certificate has expired: Monday, 20 August 2018 at 07:08:19 British Summer Time :-(

Browsers will be complaining and people pointing to https://x3dom.org/download/dev/x3dom-full.js etc will be throwing security warnings / rejected by browsers.

**Comment by splace** [comment]
yep, website now broken.

**Comment by tsturm** [comment]
fixed ;)

**Comment by jamesleesaunders** [comment]
Thanks @tsturm. As you appear to be involved in the website, is issue #603 anything you can fix easily? The documentation is duplicated many times (lots of scrolling).

**Comment by tsturm** [comment]
The mentioned link in #603 is not correct. If you use the official link:
[https://doc.x3dom.org/author/nodes.html](https://doc.x3dom.org/author/nodes.html)
It looks like expected.

**Comment by jamesleesaunders** [comment]
Excellent cool. Looks like #603 can be closed then? 
That said, surly it is still an issue this bloated/duplicate page exists? 
Going to https://doc.x3dom.org/developer/index.html -> Namaspaces -> x3dom.nodeTypes take you here. (I appreciate this is the internal developer documentation).
Ignore me if see fit, I am just looking for ways to contribute and scanning issues for any which I can possible help close down.

**Comment by tsturm** [comment]
I think I found the bug in one of the jsdoc templates and fixed it with my last commit f2c9530a6284f84e628bb73bc56c2b2c2c87ba8c

**Comment by paulmasson** [comment]
The official documentation has finally been updated! Cool!

**Comment by jamesleesaunders** [comment]
Hi guys, the x3dom.org certificate has expired again. Can it be renewed again?
